// The lifecycle definition contract (Email hub slice 11). A definition is a state-based
// nudge: "artists currently in <audienceKey> get this email once". Definitions live as code
// files under ./definitions (one file per key, regenerated by Control Tower's export
// workflow); the engine (./engine) runs the 'active' ones from the daily cron.
//
// SAFETY: a send is impossible unless BOTH process.env.EMAIL_LIFECYCLE_ENABLED === 'true'
// (checked by the cron route AND the engine) AND the definition's status is 'active'.
// Exports from Control Tower always arrive as 'draft'; flipping one to 'active' is a
// deliberate, reviewed edit.

export type LifecycleDefinition = {
  key: string; // stable slug, matches the CT registry key
  name: string;
  status: "draft" | "active"; // only 'active' runs; exports from CT always arrive 'draft'
  audienceKey: string; // a KNOWN segment execution key: who currently qualifies.
  // Segments are state-based, so leaving the state is the stop condition.
  // v1 semantics: every definition sends at most once per artist, ever — enforced by
  // the marker table's period_key 'once' + its UNIQUE constraint, not by a field here.
  throttleDays: number; // min days since ANY lifecycle send to this artist (global gate)
  preferenceCategory: "lifecycle";
  subject: string; // may contain {{tokens}}
  html: string; // INNER content html (no shell), {{tokens}} allowed
  text: string; // plain-text body, {{tokens}} allowed
};
