-- 0065 — email_lifecycle (Email hub slice 11: the lifecycle email engine)
--
-- Backs the daily lifecycle cron (/api/cron/lifecycle). Lifecycle definitions live in code
-- (src/lib/email-campaigns/lifecycle/definitions, regenerated by Control Tower's export
-- workflow); these tables carry only the per-artist send state and per-run aggregates.
-- Control Tower reads AGGREGATES of these tables through /api/internal/lifecycle-runs;
-- raw marker rows (artist ids) never leave this database. Two tables:
--   email_lifecycle_markers — one row per (definition, artist, period): the at-most-once send marker
--   email_lifecycle_runs    — one row per definition per cron run (aggregates for admin/CT visibility)
--
-- SERVICE-ROLE ONLY (same pattern as email_jobs/email_events, migrations 0063/0064): RLS is
-- enabled on both with NO policies. Every access goes through the service-role client
-- (src/lib/supabase/service.ts), which bypasses RLS. The repo is public and there is no anon
-- policy, so none of these rows can ever be read, enumerated, or modified by the public.
--
-- Additive only. Applied via `supabase db push`, dev first then prod. Never `migration repair`.

-- The at-most-once send marker. The engine INSERTS a 'pending' marker BEFORE calling Resend
-- and only then sends, so a crash between insert and send can never double-send: the stuck
-- 'pending' marker simply blocks that artist for that definition (fail-safe in the quiet
-- direction — a missed nudge, never a duplicate one). UNIQUE(definition_key, artist_id,
-- period_key) is the database-level guarantee; period_key is 'once' for every v1 definition
-- (onceOnly), reserved for future recurring definitions. 'failed' markers likewise block
-- (at-most-one ATTEMPT per artist per definition, by design).
CREATE TABLE IF NOT EXISTS email_lifecycle_markers (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  definition_key    text NOT NULL,
  artist_id         uuid REFERENCES profiles(id) ON DELETE CASCADE,
  period_key        text NOT NULL DEFAULT 'once',
  status            text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','sent','failed')),
  resend_message_id text,
  error             text,
  created_at        timestamptz DEFAULT now(),
  UNIQUE (definition_key, artist_id, period_key)
);

-- One row per definition per cron run: audience/eligible/sent/failed/skipped aggregates,
-- with the skip-reason breakdown in skipped_detail (no_email / suppressed / opted_out /
-- throttled / already_sent / capped). Read by /api/internal/lifecycle-runs for CT polling.
CREATE TABLE IF NOT EXISTS email_lifecycle_runs (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  definition_key    text NOT NULL,
  status            text NOT NULL DEFAULT 'completed'
                      CHECK (status IN ('completed','failed')),
  audience_size     int,
  eligible          int,
  sent_count        int DEFAULT 0,
  failed_count      int DEFAULT 0,
  skipped_count     int DEFAULT 0,
  skipped_detail    jsonb,
  error             text,
  created_at        timestamptz DEFAULT now(),
  completed_at      timestamptz
);

-- The global throttle query: "any lifecycle marker for this artist newer than N days".
CREATE INDEX IF NOT EXISTS email_lifecycle_markers_artist_recent_idx
  ON email_lifecycle_markers (artist_id, created_at DESC);
-- The runs feed ordered newest-first (recent-runs list + latest-run-per-definition lookups).
CREATE INDEX IF NOT EXISTS email_lifecycle_runs_created_idx
  ON email_lifecycle_runs (created_at DESC);

ALTER TABLE email_lifecycle_markers ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_lifecycle_runs ENABLE ROW LEVEL SECURITY;
-- Intentionally NO policies on either: all access is via the service-role client, which
-- bypasses RLS. There is no anon/user path to lifecycle markers or run aggregates.
