// GENERATED FILE - regenerated by Control Tower's Email hub export workflow from the
// contents of this directory. Hand edits to the ARRAY survive only until the next export;
// edit the individual definition files instead.
import type { LifecycleDefinition } from "../types";
import { definition as setup_incomplete_nudge } from "./setup_incomplete_nudge";

export const LIFECYCLE_DEFINITIONS: LifecycleDefinition[] = [
  setup_incomplete_nudge,
];
