// GENERATED FILE - regenerated by Control Tower's Email hub export workflow from the
// contents of this directory (files named [a-z0-9_]+.ts; anything else is skipped).
// Hand edits to the ARRAY survive only until the next export; edit the definition files.
import type { LifecycleDefinition } from "../types";

export const LIFECYCLE_DEFINITIONS: LifecycleDefinition[] = [];
